package UI;

import com.sun.javafx.fxml.expression.BinaryExpression;
import logica.OS;

public class InicializadorMemoria extends javax.swing.JFrame {

    OS OS;
    
    public InicializadorMemoria() {
        this.setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iniciar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paginaField = new javax.swing.JTextField();
        mpField = new javax.swing.JTextField();
        msField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciar.setText("Continuar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel3.setText("Kb. Tamaño de M. Principal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 170, 20));

        jLabel9.setText("Mb. Tamaño de M. Secundaria");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 20));

        jLabel10.setText("Kb. Tamaño de página/marco");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, 20));

        paginaField.setText("1");
        getContentPane().add(paginaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 30));

        mpField.setText("16");
        getContentPane().add(mpField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, -1));

        msField.setText("1");
        getContentPane().add(msField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 140, -1));

        jLabel1.setText("Los números ingresados deben ser potencias de 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean isPow(double test){
        double test1 = test;
        while(true){
            if(test1 == 1){
                return true;
            }
            if(test1%2 != 0){ //No es potencia de 2
                return false;
            }
            test1 = test1 / 2;
        }
    }
    
    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        double tamMarco, tamMP, tamMS;
        boolean pasar = true;
        
        if(this.mpField.getText().length() > 0 && this.msField.getText().length() > 0 && this.paginaField.getText().length() > 0){
                //Validar tamMarco
            tamMarco = Integer.parseInt(this.paginaField.getText());
            pasar = this.isPow(tamMarco);
            
            if(pasar){
                tamMP = Integer.parseInt(this.mpField.getText());
                pasar = this.isPow(tamMP);
                
                if(pasar){
                    
                    tamMS = Integer.parseInt(this.msField.getText());
                    pasar = this.isPow(tamMS);

                    if(pasar){
                            //Verificar que mp no es mayor a ms
                        if((tamMP*1024) >= (tamMS*1024*1024)){
                            System.out.println("Add JOptionPane de mp es mayor a mp");
                            return;
                        }
                            //Verificar que el número de marcos es mayor o igual a 16
                        if((tamMarco*16) > tamMP){
                            System.out.println("Add JOptionPane de el tamaño de página es muy grande para la mp");
                            return;
                        }
                            //Verificar que el número de marcos es menor o igual a 256
                        if((tamMarco*256) < tamMP){
                            System.out.println("Add JOptionPane de el tamaño de página es muy pequeño para la mp");
                            return;
                        }
                        
                        tamMarco = tamMarco*1024; //Trabajar en bytes
                        tamMP = tamMP*1024; //Trabajar en bytes
                        tamMS = tamMS*1024*1024; //Trabajar en bytes
                        
                        this.OS = new OS(tamMarco, tamMP, tamMS);
                        
                        InicializadorProcesos exe = new InicializadorProcesos(this.OS);
                        this.setVisible(false);
                    }else{
                        System.out.println("Add JOptinoPane de tamaño de ms no es potencia de 2");
                    }
                }else{
                    System.out.println("Add JOptinoPane de tamaño de mp no es potencia de 2");
                }
            }else{
                System.out.println("Add JOptinoPane de tamaño de página no es potencia de 2");
            }
        }else{
            System.out.println("Add JOptinoPane de campos inválidos");
        }
        
    }//GEN-LAST:event_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicializadorMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicializadorMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicializadorMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicializadorMemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicializadorMemoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mpField;
    private javax.swing.JTextField msField;
    private javax.swing.JTextField paginaField;
    // End of variables declaration//GEN-END:variables
}
