package UI;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;
import logica.Interfaz;

public class UIEjecucion extends javax.swing.JFrame {

    Interfaz OS;
        //Celdas de memoria
    JTextField[] celdas;
        //Label de celdas de memoria
    JLabel[] labelCeldas;
    
    public UIEjecucion(Interfaz OS) {
        
        initComponents();
        
        this.OS = OS;
        this.setVisible(true);
        
        int posX = this.mempLabel.getX();
        int posY = this.mempLabel.getY()+40;
        int tamMarco = this.OS.getTamMarco();
        
        //Desplegar arreglo de memoria
        this.celdas = new JTextField[this.OS.getNumMarcos()];
        this.labelCeldas = new JLabel[this.OS.getNumMarcos()];
        
        for(int i=0;i<this.celdas.length;i++){
            this.celdas[i] = new JTextField();
            this.celdas[i].setLocation(this.mempLabel.getX(), posY);
            this.celdas[i].setFocusable(false);
            this.celdas[i].setBackground(Color.green);
            this.labelCeldas[i] = new JLabel();
            this.labelCeldas[i].setLocation((this.celdas[i].getX()-20), posY);
            this.labelCeldas[i].setText(""+i);
            getContentPane().add(this.celdas[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(posX, posY, 50, 15));
            getContentPane().add(this.labelCeldas[i], new org.netbeans.lib.awtextra.AbsoluteConstraints(posX-20, posY, 25, 15));
            posY+=15;
            if(i % 32 == 31){
                posX+=75;
                posY-=(32*15);
            }
        }
        this.setSize(posX+230 , ((this.mempLabel.getY()+90+(32*15))));
        
        double aux = this.OS.getTamMP();
        if(aux/(1024*1024)>1){
            aux = (aux/(1024*1024));
            this.mempLabel.setText("Memoria Principal: "+aux+" Mb");
        }else{
            aux = (aux/1024);
            this.mempLabel.setText("Memoria Principal: "+aux+" Kb");
        }
        
        aux = this.OS.getTamMarco()/1024;
        this.marcoLabel.setText("Tamaño del Marco: "+aux+" Kb");
        
        aux = this.OS.getTamMS();
        if(aux/(1024*1024*1024)>=1){
            aux = aux/(1024*1024*1024);
            this.memsLabel.setText("Memoria Secundaria: "+aux+" Gb");
        }else{
            aux = aux/(1024*1024);
            this.memsLabel.setText("Memoria Secundaria: "+aux+" Mb");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mempLabel = new javax.swing.JLabel();
        marcoLabel = new javax.swing.JLabel();
        memsLabel = new javax.swing.JLabel();
        elimnLabel = new javax.swing.JLabel();
        elimCampo = new javax.swing.JTextField();
        eliminar = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        addLabel = new javax.swing.JLabel();
        tamLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        idCampo = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        suspLabel = new javax.swing.JLabel();
        suspCampo = new javax.swing.JTextField();
        susp = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Procesos: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        mempLabel.setText("Memoria Principal:");
        getContentPane().add(mempLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 230, 20));

        marcoLabel.setText("Tamaño del Marco:");
        getContentPane().add(marcoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 220, 20));

        memsLabel.setText("Memoria Secundaria:");
        getContentPane().add(memsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 270, 20));

        elimnLabel.setText("Eliminar por ID:");
        getContentPane().add(elimnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 20));

        elimCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimCampoActionPerformed(evt);
            }
        });
        getContentPane().add(elimCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 140, -1));

        eliminar.setText("Eliminar");
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 90, -1));

        idLabel.setText("ID:");
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 80, 20));

        addLabel.setText("Agregar:");
        getContentPane().add(addLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        tamLabel.setText("Tamaño:       2                  bytes");
        getContentPane().add(tamLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 160, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel1.setText("Desde 2 Kb hasta 8 Mb");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 130, 20));
        getContentPane().add(idCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 190, -1));

        agregar.setText("Añadir");
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        suspLabel.setText("Suspender por ID:");
        getContentPane().add(suspLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, 20));
        getContentPane().add(suspCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 140, -1));

        susp.setText("Suspender");
        getContentPane().add(susp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elimCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elimCampoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField elimCampo;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel elimnLabel;
    private javax.swing.JTextField idCampo;
    private javax.swing.JLabel idLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel marcoLabel;
    private javax.swing.JLabel mempLabel;
    private javax.swing.JLabel memsLabel;
    private javax.swing.JButton susp;
    private javax.swing.JTextField suspCampo;
    private javax.swing.JLabel suspLabel;
    private javax.swing.JLabel tamLabel;
    // End of variables declaration//GEN-END:variables
}
